stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: tarcinapp/entity-persistence-service:v1
      registry: bulutarti.com/private/registry
- name: Add YAML
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: |-
        cat <<EOT >> greetings.txt
        line 1
        line 2
        EOT
        ls
timeout: 60
notification: {}
