stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: tarcinapp/entity-persistence-service:${CICD_EXECUTION_SEQUENCE}
      registry: bulutarti.com/private/registry
    env:
      PLUGIN_MTU: 1450
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
    env:
      APP_NAME: entity-persistence
timeout: 60
notification: {}
