stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: tarcinapp/entity-persistence-service
      registry: bulutarti.com/private/registry
timeout: 60
notification: {}
