stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: tarcinapp/entity-persistence-service:${CICD_EXECUTION_SEQUENCE}
    env:
      PLUGIN_MTU: "1450"
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./k8s/deployment-test.yaml
    when:
      branch:
        include:
        - dev
timeout: 60
notification: {}
