stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: tarcinapp/entity-persistence-service:v1
      registry: bulutarti.com/private/registry
- name: Add YAML
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: |-
        cat <<EOT >> deployment.yaml
        kind: Service
        apiVersion: v1
        metadata:
          name: ${APP_NAME}-service
        spec:
          selector:
            app: ${APP_NAME}
          type: NodePort
          ports:
            - protocol: TCP
              port: 80
              targetPort: 3000
        ---
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: example-${APP_NAME}
          labels:
            app: ${APP_NAME}
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: ${APP_NAME}
          template:
            metadata:
              labels:
                app: ${APP_NAME}
            spec:
              imagePullSecrets:
              - name: pipeline-docker-registry
              containers:
              - name: helloserver
                image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
                ports:
                - containerPort: 3000
        EOT
        ls
timeout: 60
notification: {}
