kind: Service
apiVersion: v1
metadata:
  name: entity-persistence-service
  namespace: tarcinapp-test
spec:
  selector:
    app: entity-persistence
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: entity-persistence-deployment
  namespace: tarcinapp-test
  labels:
    app: entity-persistence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: entity-persistence
  template:
    metadata:
      labels:
        app: entity-persistence
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: entity-persistence
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        env:
        - name: ADMIN_ROLE_NAMES
          value: "tarcinapp_admin,tarcinapp_editor"
        - name: MEMBER_ROLE_NAMES
          value: tarcinapp_member
        - name: ALLOWED_ENTITY_KINDS
          value: "firma,urun,parti,siyasetci,marka,model"
        - name: AUTO_APPROVE_ENTITIES_CREATED_BY_MEMBERS
          value: "false"
        - name: ALLOWED_REACTION_KINDS
          value: "comment,like,subcomment,comment_like,comment_dislike"
        - name: ALLOWED_RELATION_KINDS
          value: "produces,owner_person,owner_company,brand"
        - name: AUTO_APPROVE_REACTIONS_CREATED_BY_MEMBERS
          value: "true"
        - name: ALLOWED_LIST_TYPES
          value: "saved_entities,saved_lists,featured_by_members,public_list,featured_by_editors"
        - name: AUTO_APPROVE_LISTS_CREATED_BY_MEMBERS
          value: "false"
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /ping
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 60
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
