kind: Service
apiVersion: v1
metadata:
  name: entity-persistence-service
  namespace: tarcinapp-live
spec:
  selector:
    app: entity-persistence
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: entity-persistence-deployment
  namespace: tarcinapp-live
  labels:
    app: entity-persistence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: entity-persistence
  template:
    metadata:
      labels:
        app: entity-persistence
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - name: entity-persistence
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /ping
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 60
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: ENV
              value: live
          envFrom:
            - configMapRef:
                name: entity-persistence-service-config
            - secretRef:
                name: entity-persistence-service-secret
